from PyQt5 import QtCore, QtGui, QtWidgets

BUTTON_STYLE = """QPushButton {
    background-color: #d3311b;
    border : none;
    color : white;
}"""


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 881)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_9 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_9.setGeometry(QtCore.QRect(200, 680, 141, 36))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 80, 61, 20))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/resources/resources/arrow.png"))
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 120, 141, 36))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 520, 311, 36))
        self.textEdit_4.setObjectName("textEdit_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-10, 20, 411, 51))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.widget.setObjectName("widget")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(170, 15, 81, 22))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(20, 15, 21, 20))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/resources/resources/leftarrow.png"))
        self.label_11.setScaledContents(False)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(40, 15, 67, 22))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setGeometry(QtCore.QRect(380, 15, 67, 22))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/resources/resources/user_circular.png"))
        self.label_13.setObjectName("label_13")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(200, 200, 171, 36))
        self.spinBox.setSuffix("")
        self.spinBox.setMinimum(1990)
        self.spinBox.setMaximum(2022)
        self.spinBox.setObjectName("spinBox")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(200, 360, 141, 36))
        self.textEdit_3.setObjectName("textEdit_3")
        self.comboBox_10 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_10.setGeometry(QtCore.QRect(10, 760, 141, 36))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(10, 600, 311, 36))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 280, 141, 36))
        self.textEdit.setObjectName("textEdit")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(200, 120, 141, 36))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setGeometry(QtCore.QRect(200, 440, 141, 36))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(10, 200, 141, 36))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(50, 80, 91, 22))
        self.label_14.setObjectName("label_14")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(200, 280, 141, 36))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(10, 440, 141, 36))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_8.setGeometry(QtCore.QRect(10, 680, 141, 36))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(160, 80, 111, 22))
        self.label_15.setObjectName("label_15")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 360, 141, 36))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(-30, 70, 61, 51))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/resources/resources/home.png"))
        self.label_16.setScaledContents(False)
        self.label_16.setObjectName("label_16")
        self.button1_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button1_6.setGeometry(QtCore.QRect(100, 820, 181, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 49, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 49, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 161, 163))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 49, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 171, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 38, 41, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.button1_6.setPalette(palette)
        self.button1_6.setAcceptDrops(False)
        self.button1_6.setObjectName("button1_6")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(0, 0, 431, 22))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap(":/resources/resources/phone_status_bar.png"))
        self.label_17.setObjectName("label_17")
        self.textEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_6.setGeometry(QtCore.QRect(200, 760, 141, 36))
        self.textEdit_6.setObjectName("textEdit_6")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(130, 80, 61, 20))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/resources/resources/arrow.png"))
        self.label_18.setObjectName("label_18")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox_9.setPlaceholderText(_translate("MainWindow", "Interior Color"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "Beige"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "Black"))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "Brown"))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "Grey"))
        self.comboBox_9.setItemText(4, _translate("MainWindow", "White"))
        self.comboBox_9.setItemText(5, _translate("MainWindow", "Other"))
        self.comboBox.setPlaceholderText(_translate("MainWindow", "Category"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Hatchback"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Coupe"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Roadster"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4x4 / Jeep / SUV"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Supercar"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Van / Mini Bus"))
        self.textEdit_4.setPlaceholderText(_translate("MainWindow", "City Fuel Consumption (L / 100 Km)"))
        self.label_10.setText(_translate("MainWindow",
                                         "<html><head/><body><p><span style=\" color:#d3311b;\">Post Listing</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow",
                                         "<html><head/><body><p><span style=\" color:#d3311b;\">Back</span></p></body></html>"))
        self.spinBox.setPrefix(_translate("MainWindow", "Release Year:  "))
        self.textEdit_3.setPlaceholderText(_translate("MainWindow", "Power (bhp)"))
        self.comboBox_10.setPlaceholderText(_translate("MainWindow", "# Doors"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "2"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "3"))
        self.comboBox_10.setItemText(2, _translate("MainWindow", "4"))
        self.comboBox_10.setItemText(3, _translate("MainWindow", "5"))
        self.comboBox_10.setItemText(4, _translate("MainWindow", "6"))
        self.comboBox_10.setItemText(5, _translate("MainWindow", "7"))
        self.textEdit_5.setPlaceholderText(_translate("MainWindow", "Motorway Fuel Consumption (L / 100 Km)"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Mileage (Km)"))
        self.comboBox_2.setPlaceholderText(_translate("MainWindow", "Company"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Alfa Romeo"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Audi"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "BMW"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Chevrolet"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Citroen"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "Dodge"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "Ferrari"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "Ford"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "Hyundai"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "Jaguar"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "Mazda"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "Mercedes-Benz"))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "Mitsubishi"))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "Nissan"))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "Opel"))
        self.comboBox_2.setItemText(15, _translate("MainWindow", "Peugeot"))
        self.comboBox_2.setItemText(16, _translate("MainWindow", "Porsche"))
        self.comboBox_2.setItemText(17, _translate("MainWindow", "Subaru"))
        self.comboBox_2.setItemText(18, _translate("MainWindow", "Toyota"))
        self.comboBox_2.setItemText(19, _translate("MainWindow", "Volkswagen"))
        self.comboBox_2.setItemText(20, _translate("MainWindow", "Volvo"))
        self.comboBox_7.setPlaceholderText(_translate("MainWindow", "Fuel Type"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Diesel"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "Gas"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "Petrol"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "Electric"))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "Hybrid"))
        self.comboBox_4.setPlaceholderText(_translate("MainWindow", "Model"))
        self.label_14.setText(_translate("MainWindow",
                                         "<html><head/><body><p><span style=\" color:#d3311b;\">Post Listing</span></p></body></html>"))
        self.comboBox_5.setPlaceholderText(_translate("MainWindow", "Condition"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "New"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Used"))
        self.comboBox_6.setPlaceholderText(_translate("MainWindow", "Transmission"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Manual"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Automatic"))
        self.comboBox_8.setPlaceholderText(_translate("MainWindow", "Color"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "Black"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "Blue"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "Brown"))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "Green"))
        self.comboBox_8.setItemText(4, _translate("MainWindow", "Grey"))
        self.comboBox_8.setItemText(5, _translate("MainWindow", "Red"))
        self.comboBox_8.setItemText(6, _translate("MainWindow", "White"))
        self.label_15.setText(_translate("MainWindow",
                                         "<html><head/><body><p><span style=\" color:#d3311b;\">Vehicle Details</span></p></body></html>"))
        self.textEdit_2.setPlaceholderText(_translate("MainWindow", "Engine (cc)"))
        self.button1_6.setText(_translate("MainWindow", "Continue"))
        self.textEdit_6.setPlaceholderText(_translate("MainWindow", "Registration Plate"))


import app_res_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    app.setStyleSheet(BUTTON_STYLE)
    MainWindow = QtWidgets.QMainWindow()
    MainWindow.setStyleSheet("QMainWindow {background: 'white';}")
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
